# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en
locales: [ca, en, es]
ignore_missing:
  - "errors.messages.uppercase_only_letters_numbers"
  - "devise.registrations.*"
  - "decidim.devise.registrations.*"
  - "decidim.verifications.authorizations.*"

ignore_unused:
  - "activemodel.attributes.user.document_number"
  - "devise.registrations.user.error"
  - "decidim.authorization_handlers.crm_authenticable_authorization_handler.*"
